### PR TITLE
token-ask

### PR DESCRIPTION
**Pull request by rosidae**
asks user for their token, writes token to a file, uses the token from that file.

### CODE REVIEW

**Comment by MainSilent** [comment]
There is a better approach. Instead of having a token file at first with the text `none`, We can check if the file exists in the working directory and read the token or else create the token file and ask the user..., So we don't need to push the file `token`.

**Comment by rosidae** [comment]
updated to use better approach 46c59725a72fcedb84dda9847dac41329b4b3c51

**Comment by MainSilent** [comment]
There is one bug, When the input requests the token and we exist the program it will create an empty token file because we are first creating the file and then asking for input. In the `if` condition first ask and store the token and then create and write to the file.

**Comment by rosidae** [comment]
Addressed in 85428ab4fef981f3f98c395eaaab13e9b3d6da4d

**Comment by MainSilent** [comment]
That's a good commit

**Pull request merged**
